name: Deplot On Push

on:
    push:
        branches:
            -main

jobs:
    check:
        runs-on: ubuntu-lastest
        steps:
            - name: Testing
              run: |
                 echo "Testing CI/CD pipeline"
                 echo "Testing CI/CD pipeline 2"